name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04  

stages:
- stage: publish
  displayName: publish
  jobs:
  - template: publish-and-download-k8s-artefact.yml     

- stage: qa
  displayName: 'qa'
  jobs:
  - template: megastore-message-queue-stage.yml

- stage: prd
  displayName: 'prd'
  dependsOn: qa
  condition: succeeded('qa')  
  jobs:
  - template: megastore-message-queue-stage.yml