parameters:
  environmentName: ''

jobs:
  - deployment: deploy_to_stage
    displayName: 'deploy_to_stage'
    environment: ${{parameters.environmentName}}
    workspace:
      clean: all    
    strategy:
      runOnce:
        deploy:
          steps:

            - template: output-variable-values.yml
          
            - task: DownloadSecureFile@1
              name: config
              inputs:
                secureFile: config

            - script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f $SYSTEM_DEFAULTWORKINGDIRECTORY/$K8SCONFIGPATH/message-queue-service.yaml --namespace=$SYSTEM_STAGENAME
              displayName: 'apply service for stage'

            - script: kubectl --kubeconfig $AGENT_TEMPDIRECTORY/config apply -f $SYSTEM_DEFAULTWORKINGDIRECTORY/$K8SCONFIGPATH/message-queue-deployment.yaml --namespace=$SYSTEM_STAGENAME
              displayName: 'apply deployment for stage'