name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04  

stages:
- stage: build
  displayName: 'build'
  variables:
  - name: service_name
    value: 'megastore.savesalehandler'
  - name: image_name
    value: 'megastoresavesalehandler'    
  jobs:
  - template: publish-and-download-k8s-artefact.yml
  
  - template: megastore-build-push-image.yml
    parameters:
      ServiceName: $(service_name)
      ImageName: $(image_name)

# - stage: qa
#   displayName: 'qa'
#   dependsOn: build
#   condition: succeeded('build')  
#   jobs:
#   - template: megastore-savesalehandler-stage.yml
#     parameters:
#       environmentName: $(EnvironmentNameQa)

# - stage: prd
#   displayName: 'prd'
#   dependsOn: qa
#   condition: succeeded('qa')  
#   jobs:
#   - template: megastore-savesalehandler-stage.yml
#     parameters:
#       environmentName: $(EnvironmentNamePrd)      