name: '0.1.$(Rev:r)'

trigger: none

variables:
- group: megastore

pool:
  name: local
  demands:
  - agent.name -equals ubuntu-18.04

stages:
- stage: publish
  displayName: publish
  jobs:
  - job: publish_artefact_then_download
    workspace:
      clean: all
    steps:

    - template: output-variable-values.yml    

    - publish: $(System.DefaultWorkingDirectory)/k8s
      artifact: k8s
      displayName: 'publish k8s artefact'

    - download: current
      artifact: k8s
      displayName: 'download k8s artefact'            

- stage: qa
  displayName: qa
  variables:
  - name: app_insights_instrumentation_key
    value: $(app_insights_instrumentation_key_qa)
  jobs:
  - template: megastore-init-stage.yml
    parameters:
      app_insights_instrumentation_key: $(app_insights_instrumentation_key)

- stage: prd
  displayName: prd
  variables:
  - name: app_insights_instrumentation_key
    value: $(app_insights_instrumentation_key_prd)
  jobs:
  - template: megastore-init-stage.yml
    parameters:
      AppInsightsInstrumentationKey: $(app_insights_instrumentation_key)