version: '3.4'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=0dd2173e-84cb-4920-ac59-bb26dec38542
    ports:
      - 80
    depends_on:
      - message-queue
    networks:
      - ms-net

  megastore.savesalehandler:
    environment:
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=0dd2173e-84cb-4920-ac59-bb26dec38542
    env_file:
      - db-credentials.env
    depends_on:
      - message-queue
    networks:
      - ms-net

networks:
  ms-net: